spring:
  datasource:
    url:jdbc:mysql://localhost:3306/netctoss?serverTimezone=UTC&allowMultiQueries=true
    username:netctoss
    password:123456
    driver-class-name:com.mysql.cj.jdbc.Driver
server:
  port: 8083